<?php

// Slice D outputs (spec §7 P5.1–P5.3). Routes pre-wired by the integrator;
// controllers are implemented per-ticket — do not edit this file from
// ticket branches.

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

Route::middleware(['web', 'auth', 'admin'])->group(function () {
    foreach ([
        'pullsheets', 'labels', 'bottle_label', 'table_cards', 'sorting',
        'shipping_label', 'participant_summary',
        'participant_entries_list', 'post_judge_inventory', 'judge_notes',
        'assignments', 'staff_points', 'styles', 'maps', 'dropoff', 'print',
        'entries_print',
        'results', 'bos_mat', 'scoresheets', 'export',
    ] as $output) {
        // Register only controllers that exist: lets the route file load
        // while Slice D controllers land incrementally; all 21 exist at
        // integration, so nothing is skipped in the final app.
        $cls = 'App\Http\Controllers\Output\\'.Str::studly($output).'Controller';
        if (class_exists($cls)) {
            Route::get('/admin/output/'.$output, ['\\'.$cls, '__invoke'])
                ->name('outputs.'.$output);
        } elseif (! app()->isProduction()) {
            // A missing controller used to drop its route silently, so the
            // dashboard link 404'd with nothing pointing at the cause. Fail
            // loudly everywhere except production, where a boot error would
            // take the whole site down.
            throw new RuntimeException("Output controller {$cls} is missing; route outputs.{$output} would be dropped.");
        }
    }
});
